### ISSUE TITLE
The problem is me or the lib?

### ISSUE THREAD

**Issue by hiwyn** [gemini-testing/looks-same#80]
Trying to test the lib, but got some error

Test script:
```js
import looksSame from "looks-same";

async function CompareTwoImages2() {
  looksSame(
    looksSame("cropped.png", "mace.png", function (error, { equal }) {
      console.log(error);
      console.log(equal);
    })
  );
}
CompareTwoImages2();
```

Error:
```
(node:5032) UnhandledPromiseRejectionWarning: TypeError: Field "source" does not exist in {}
    at /home/hiwyn/playimg/node_modules/looks-same/lib/validators.js:9:19
    at Array.forEach (<anonymous>)
    at validateRequiredFields (/home/hiwyn/playimg/node_modules/looks-same/lib/validators.js:7:23)
    at /home/hiwyn/playimg/node_modules/looks-same/lib/validators.js:30:9
    at Array.forEach (<anonymous>)
    at Object.exports.validateImages (/home/hiwyn/playimg/node_modules/looks-same/lib/validators.js:25:18)
    at Object.exports.formatImages (/home/hiwyn/playimg/node_modules/looks-same/lib/utils.js:84:16)
    at looksSame (/home/hiwyn/playimg/node_modules/looks-same/index.js:147:30)
    at CompareTwoImages2 (file:///home/hiwyn/playimg/test.js:4:3)
    at file:///home/hiwyn/playimg/test.js:11:1
(node:5032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
null
false
```

**Comment by DudaGod** [comment]
Hello.

Problem in your code. You should not call `looksSame` with result from another call - `looksSame`. Moreover you should use `await` before call `looksSame` function. So your code should be as follows:
```
import looksSame from "looks-same";

(async () => {
    await looksSame("cropped.png", "mace.png", function (error, { equal }) {
      console.log(error);
      console.log(equal);
    })
})();
```

**Comment by hiwyn** [comment]
Thanks!
